### ISSUE TITLE
Add project to Graylog Marketplace

### ISSUE THREAD

**Issue by joschi** [jeremymcgee73/PSGELF#1]
Thanks for providing this library for the Graylog/GELF ecosystem!

It would be great if you could add it to the [Graylog Marketplace](https://marketplace.graylog.org/), so that other users can find it faster. 😄

**Comment by jeremymcgee73** [comment]
Awesome! Thanks! I added it to the Marketplace. I did that with my Big IP content pack but must have slipped my mind on this.
