### ISSUE TITLE
Specify source using variable

### ISSUE THREAD

**Issue by okay-scam** [jeremymcgee73/PSGELF#3]
Going to go right ahead and start this with the fact that this is the first time I've been exposed to GELF, and my first time sending something other than syslog data to GrayLog so apologies if this isn't supported.

Is it possible to add a variable (or I can modify your code locally) to specify the source?
It's using hostname of our Window's PCs and I want to use their Serial Number.

**Comment by jeremymcgee73** [comment]
Yeah, you can just use the parameter -hostname. Here is an example.

`Send-PSGelfTCP -GelfServer graylog -Port 12202 -ShortMessage "This is a short Message" -HostName "3c:34:34"`

**Comment by okay-scam** [comment]
I tried that, GrayLog still listed the source as the HostName. No problem though, thanks for the reply!

**Comment by jeremymcgee73** [comment]
Can you post an example of the command you are trying to use? Did you try my example above? That for sure worked in my environment.

**Comment by okay-scam** [comment]
It was user error... (me!) -host instead of -hostname.

Love the module, works like an absolute charm and thanks for the support!
