### ISSUE TITLE
Timestamp in GELF Spec 1.1 Changed

### ISSUE THREAD

**Issue by awickham10** [jeremymcgee73/PSGELF#5]
The timestamp property in the GELF spec changed from a string in 1.0 to a float in 1.1, causing errors in Graylog's `/var/log/graylog-server/server.log` file.

**Sample Error**
```
2018-12-02T05:26:29.640-05:00 WARN  [GelfCodec] GELF message <bb486080-f61c-11e8-b586-0050569965cf> (received from <XXX.XXX.XXX.XXX:YYYYY>) has invalid "timestamp": 1543746383.09804  (type: STRING)
```

**Comment by jeremymcgee73** [comment]
Hmm. I will do some research on this. I wonder if we will need a parameter to set which spec is being used. I also wonder which one should be the default. Any thoughts?

**Comment by awickham10** [comment]
It looks like 1.1 was released in November, 2013, so I would probably lean towards defaulting to 1.1.

**Comment by jeremymcgee73** [comment]
Thanks @awickham10 for letting me know. Can you try the current version on github? If everything looks good, I will release to the gallery. I did some quick testing on it. I changed the timestamp to be a double. The pester tests need some work...

**Comment by ion-storm** [comment]
@jeremymcgee73 I just cloned this repo and am testing with Graylog 2.5, and I get the same error:
WARN  [GelfCodec] GELF message <699d51a0-18d1-11e9-9d28-0050569f0457> (received from <172.XX.42.XX:57966>) has invalid "timestamp": 1544803194.59746  (type: STRING)

**Comment by ion-storm** [comment]
to reproduce try to run Get-WinEvent Setup -MaxEvents 10 | Send-PSGelfTCPFromObject -GelfServer graylog -Port 12202
this doesnt create the timestamp field as a double

**Comment by jeremymcgee73** [comment]
I have fixed the issue. I just needed to cast the timestamp as a double. This removes the quotes around the timestamp when you convert to JSON. 👍
